/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    Converter: typeof import('./src/components/Converter.vue')['default']
    DockerConf: typeof import('./src/components/DockerConf.vue')['default']
    PodmanConf: typeof import('./src/components/PodmanConf.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
