# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ["main"]
        tags: ["v*.*.*"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        strategy:
            matrix:
                node-version: [lts/jod]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: Install node modules
              run: yarn install --frozen-lockfile
            - name: Build node project
              run: |
                cp .env.example .env
                yarn build
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: dist
            - name: Compress built files
              if: startsWith(github.ref, 'refs/tags/')
              run: tar -cJvf dist.tar.xz dist
            - name: Publish new release
              if: startsWith(github.ref, 'refs/tags/')
              uses: softprops/action-gh-release@v2
              with:
                  name: Release ${{ github.ref_name }}
                  files: dist.tar.xz
